### ISSUE TITLE
A propos du site 

### ISSUE THREAD

**Issue by augustev005** [SylvioSLV/Mon-portfolio#1]
*j'aime bien ton site:
 -ton site est parfaitement structuré , tu as bien choisi les couleurs de ton site, le design est parfait , le fond et la forme de ton site sont bien structurés
-ta maquette et ton prototype ont été bien fait.

....Mais j'ai quelques remarques à te faire:
-ça serait mieux de fixer ta barre de navigation enfin que l'utilisateur ne retourne pas à chaque fois à l'accueil pour changer de menu
-là où t'as écrit "le nom; email et de" essaie de le mettre sur la même ligne et en bas également  de ton site au niveau du footer là où t'as mis "tel".

**Comment by SylvioSLV** [comment]
Bien reçu tes remarques. Merci.

**Comment by SylvioSLV** [comment]
Toutes les remarques ont été pris en compte.
